---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bara-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bara-ui
  template:
    metadata:
      labels:
        app: bara-ui
    spec:
      containers:
      - name: bara-ui
        image: lionel411/bara-ui:25245da36654b6872ec896eef25cd77218fd6a7d
        ports:
        - containerPort: 80